const VERSION='76-full-option-text';
const CONTENT_VERSION='76';
const CACHE='lousa-de-estudos-v'+VERSION;
const ASSETS=['./start.html','./index.html','./v52.html','./loader-v55.js?v=69legacy','./v68.html','./loader-v76.js?v=76','./v37.css?v=76','./v37.js?v=76','./v41.js?v=76','./v50.js?v=76','./pwa-v39.css?v=76','./pwa-v52.js?v=70install-auto','./v54.js?v=76','./v55.js?v=76','./v56.js?v=76','./v57.js?v=76','./v58.js?v=76','./v59.js?v=76','./v60.js?v=76','./v62.js?v=76','./v63.js?v=76','./v64.js?v=76','./v65.js?v=76','./v66.js?v=76','./v67.js?v=76','./v68.js?v=76','./v69.js?v=76','./v70-data-01.js?v=76','./v70-data-02.js?v=76','./v70-data-03.js?v=76','./v70-data-04.js?v=76','./v70-data-05.js?v=76','./v70-data-06.js?v=76','./v70-data-07.js?v=76','./v70-data-08.js?v=76','./v70-data-09.js?v=76','./v70-data-10.js?v=76','./v70-data-11.js?v=76','./v70.js?v=76','./v71.js?v=76','./v72.js?v=76','./v73.js?v=76','./v74.js?v=76','./v75.js?v=76','./v76.js?v=76','./v55-auto-update.js?v=76','./manifest.webmanifest?v=76','./icons/lousa-icon-192.png?v=76','./icons/lousa-icon-512.png?v=76'];
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);await cache.addAll(ASSETS);})());});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('lousa-de-estudos-v')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();})());});
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting();});
async function networkFirst(request){try{const response=await fetch(request,{cache:'no-store'});if(response&&response.ok){const cache=await caches.open(CACHE);cache.put(request,response.clone()).catch(()=>{});}return response;}catch(error){const cached=await caches.match(request,{ignoreSearch:true});if(cached)return cached;throw error;}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(url.pathname.endsWith('/app-version.json')||url.pathname.endsWith('/start.html')||url.pathname.endsWith('/v52.html')||url.pathname.endsWith('/loader-v55.js')||url.pathname.endsWith('/v68.html')||url.pathname.endsWith('/loader-v76.js')||url.pathname.endsWith('/v76.js')){event.respondWith(networkFirst(request));return;}if(request.mode==='navigate'){event.respondWith((async()=>{try{const response=await fetch(request,{cache:'no-store'});if(response&&response.ok){const cache=await caches.open(CACHE);cache.put(request,response.clone()).catch(()=>{});return response;}}catch(error){}return (await caches.match('./start.html',{ignoreSearch:true}))||(await caches.match('./v68.html',{ignoreSearch:true}))||networkFirst(request);})());return;}event.respondWith(networkFirst(request));});
