/* Lousa de Estudos v90 — Ensino Religioso fiel aos dois materiais */
(()=>{
if(window.__lousaV90ReligionExact)return;window.__lousaV90ReligionExact=true;
const V=90,SEP='§';
const JP_DATA=window.__v90JP_DATA||'',DN_DATA=window.__v90DN_DATA||'';
const JP_PASSAGE=window.__v90JP_PASSAGE||'',DN_PASSAGE=window.__v90DN_PASSAGE||'';
function qs(data,prefix){return data.split('\n').filter(Boolean).map((line,i)=>{const [text,answer,w1,w2]=line.split(SEP),pos=(i+1)%3,opts=[null,null,null],free=[0,1,2].filter(x=>x!==pos);opts[pos]=answer;opts[free[0]]=w1;opts[free[1]]=w2;return{id:prefix+String(i+1).padStart(2,'0'),type:'mcq',reviewLabel:'📖 Consulte o texto acima',review:'Se tiver dúvida, volte ao texto de estudo antes de marcar a alternativa.',text,options:opts,correct:pos,explanation:'Resposta correta: '+answer+'.',expected:'Resposta correta: '+answer+'.'}})}
function lessons(){return[
{key:'joao-paulo-ii',emoji:'🕊️',title:'São João Paulo II',subtitle:'perguntas do material impresso',desc:'Texto completo de estudo e as mesmas perguntas da folha.',mission:'Ensino Religioso • São João Paulo II',passageTitle:'São João Paulo II — texto completo para estudar',passage:JP_PASSAGE,passageVisual:'Karol Józef Wojtyła • fé • coragem • juventude • paz',questions:qs(JP_DATA,'rel90_jp')},
{key:'daniel',emoji:'📖',title:'Livro de Daniel',subtitle:'perguntas do material impresso',desc:'Texto completo de estudo e as mesmas perguntas da folha.',mission:'Ensino Religioso • Livro de Daniel',passageTitle:'Livro de Daniel — texto completo para estudar',passage:DN_PASSAGE,passageVisual:'Daniel • Babilônia • sonhos • fidelidade • oração • justiça',questions:qs(DN_DATA,'rel90_dn')}]} 
let fixed=null;
function install(){try{if(typeof subjects==='undefined'||!subjects)return false;const base=subjects.religion||{};if(!fixed)fixed={...base,key:'religion',title:'Ensino Religioso',emoji:'🙏',homeDescription:'Leia o texto completo e responda às perguntas exatamente como aparecem no material impresso.',hint:'💡 As respostas estão no próprio texto da lição.',chips:['São João Paulo II','Livro de Daniel','Perguntas do material impresso'],lessons:lessons(),__v90Exact:true};else fixed.lessons=lessons();try{Object.defineProperty(subjects,'religion',{configurable:true,enumerable:true,get(){return fixed},set(v){if(v&&v.__v90Exact)fixed=v}})}catch(e){subjects.religion=fixed}return true}catch(e){return false}}
function style(){if(document.getElementById('v90ReligionExactStyles'))return;const s=document.createElement('style');s.id='v90ReligionExactStyles';s.textContent='.readingText .v90StudyLead{margin:0 0 18px;padding:14px 15px;border:1px solid #d7e8dd;background:#f2fbf5;border-radius:16px;line-height:1.6;color:#284234}.readingText h3{margin:22px 0 8px;font-size:1.08em;line-height:1.35;color:#26352d}.readingText h3:first-of-type{margin-top:6px}.readingText p{margin:0 0 12px;line-height:1.72}.readingText .v90Sources{margin-top:22px;padding:12px 14px;border-radius:14px;background:#f7f7f7;border:1px solid #e5e7eb;font-size:.82em;line-height:1.55;color:#667085}';document.head.appendChild(s)}
function migrate(){try{if(localStorage.getItem('lousa:v90:religion-exact-migration')==='1')return;const rm=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&(/rel_jp|rel_dn|rel90_jp|rel90_dn/.test(k)))rm.push(k)}rm.forEach(k=>localStorage.removeItem(k));localStorage.setItem('lousa:v90:religion-exact-migration','1')}catch(e){}}
let fixing=false;function stamp(){if(fixing)return;fixing=true;try{const v=Math.max(V,Number(window.__lousaCurrentContentVersion||0),Number(document.querySelector('meta[name="app-version"]')?.content||0),Number(new URLSearchParams(location.search).get('content')||0));window.__lousaCurrentContentVersion=v;const m=document.querySelector('meta[name="app-version"]');if(m&&Number(m.content||0)!==v)m.content=String(v);if(document.documentElement.dataset.contentVersion!==String(v))document.documentElement.dataset.contentVersion=String(v);document.querySelectorAll('.lousaVersionOnly').forEach(el=>{if(el.textContent!=='v'+v)el.textContent='v'+v})}catch(e){}fixing=false}
style();migrate();install();stamp();
try{const o=new MutationObserver(()=>queueMicrotask(()=>{install();stamp()}));o.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['content','data-content-version']})}catch(e){}
[50,250,800,1600,2600,4200,5600,7000].forEach(ms=>setTimeout(()=>{install();stamp()},ms));setTimeout(()=>{document.getElementById('v90VersionBootHide')?.remove();stamp()},5600);window.addEventListener('pageshow',()=>{install();stamp()});window.addEventListener('focus',()=>{install();stamp()});window.__lousaV90Ready=true;
})();
